# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    rm -rf build
    mkdir build
  displayName: 'build dir'
- script: |
    cd build && sh ../configure
  displayName: 'configure'
- script: |
    cd build && make all
  displayName: 'make all'
- script: |
    cd build && make check
  displayName: 'make check'
