
FIND_PACKAGE(PkgConfig)

IF (PKG_CONFIG_FOUND)
    PKG_CHECK_MODULES(ZLIB zlib)
    IF (ZLIB_FOUND)
        INCLUDE_DIRECTORIES(${ZLIB_INCLUDE_DIRS})
        LINK_DIRECTORIES(${ZLIB_LIBRARY_DIRS})
    ELSE (ZLIB_FOUND)
        MESSAGE(STATUS "Did not find zlib pkgconfig..." )
    ENDIF (ZLIB_FOUND)
ENDIF (PKG_CONFIG_FOUND)
IF (NOT ZLIB_FOUND)
    FIND_PACKAGE(ZLIB REQUIRED)
    IF (ZLIB_FOUND)
        INCLUDE_DIRECTORIES(${ZLIB_INCLUDE_DIR})
        LINK_DIRECTORIES(${ZLIB_LIBRARY_DIRS})
    ENDIF (ZLIB_FOUND)
ENDIF (NOT ZLIB_FOUND)


INCLUDE_DIRECTORIES(${CMAKE_SOURCE_DIR})
LINK_DIRECTORIES(${CMAKE_BINARY_DIR}/zzip)
